from pymongo import MongoClient

# Conexão com o banco de dados
client: MongoClient = MongoClient("localhost", 27017)

# Selecionando o banco de dados
db = client["campeonatosE-sports_db"]
client.drop_database(db)

# Selecionando a coleção
pessoas = db["pessoas_tabela"]

# Inserindo pessoas

pessoas.insert_many(
    [
        {
            "_id": 1,
            "nome": "Cleriton",
            "nickname": "Aspas",
            "idade": 20,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "LOUD",
        },
        {
            "_id": 2,
            "nome": "Matias",
            "nickname": "Saadhack",
            "idade": 26,
            "pais": "Argentina",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "LOUD",
        },
        {
            "_id": 3,
            "nome": "Guilherme",
            "nickname": "Less",
            "idade": 19,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "LOUD",
        },
        {
            "_id": 4,
            "nome": "Arthur",
            "nickname": "Tuyz",
            "idade": 18,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "LOUD",
        },
        {
            "_id": 5,
            "nome": "Cauan",
            "nickname": "cauanzin",
            "idade": 17,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "LOUD",
        },
        {
            "_id": 6,
            "nome": "Math",
            "nickname": "fRod",
            "idade": 36,
            "pais": "Brasil",
            "tipo": "Tecnico",
            "jogo": "Valorant",
            "equipe" : "LOUD",
        },
        {
            "_id": 7,
            "nome": "Matheus",
            "nickname": "Mwzera",
            "idade": 22,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Furia",
        },
        {
            "_id": 8,
            "nome": "Igor",
            "nickname": "qCk",
            "idade": 21,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Furia",
        },
        {
            "_id": 9,
            "nome": "Pedro",
            "nickname": "Mazin",
            "idade": 22,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Furia",
        },
        {
            "_id": 10,
            "nome": "Henrique",
            "nickname": "khalil",
            "idade": 22,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Furia",
        },
        {
            "_id": 11,
            "nome": "Mader",
            "nickname": "dgzin",
            "idade": 24,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Furia",
        },
        {
            "_id": 12,
            "nome": "Carlos",
            "nickname": "Carlao",
            "idade": 30,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Furia",
        },
        {
            "_id": 13,
            "nome": "Mark",
            "nickname": "Tenz",
            "idade": 23,
            "pais": "Estados Unidos",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Sentinels",
        },
        {
            "_id": 14,
            "nome": "Mathell",
            "nickname": "Marved",
            "idade": 24,
            "pais": "Canada",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Sentinels",
        },
        {
            "_id": 15,
            "nome": "Thomas",
            "nickname": "zekken",
            "idade": 17,
            "pais": "Estados Unidos",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Sentinels",
        },
        {
            "_id": 16,
            "nome": "Bryan",
            "nickname": "pancAda",
            "idade": 25,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Sentinels",
        },
        {
            "_id": 17,
            "nome": "Matheus",
            "nickname": "sacy",
            "idade": 24,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Sentinels",
        },
        {
            "_id": 18,
            "nome": "Adam",
            "nickname": "Kaplan",
            "idade": 29,
            "pais": "Estados Unidos",
            "tipo": "Tecnico",
            "jogo": "Valorant",
            "equipe" : "Sentinels",
        },
        {
            "_id": 19,
            "nome": "Kelden",
            "nickname": "Boostio",
            "idade": 22,
            "pais": "Estados Unidos",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "EG",
        },
        {
            "_id": 20,
            "nome": "Max",
            "nickname": "Demon1",
            "idade": 18,
            "pais": "Estados Unidos",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "EG",
        },
        {
            "_id": 21,
            "nome": "Ethan",
            "nickname": "Ethan",
            "idade": 22,
            "pais": "Estados Unidos",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "EG",
        },
        {
            "_id": 22,
            "nome": "Corbin",
            "nickname": "COM",
            "idade": 20,
            "pais": "Estados Unidos",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "EG",
        },
        {
            "_id": 23,
            "nome": "Alexander",
            "nickname": "JAWGEMO",
            "idade": 21,
            "pais": "Estados Unidos",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "EG",
        },
        {
            "_id": 24,
            "nome": "Christine",
            "nickname": "Potter",
            "idade": 26,
            "pais": "Estados Unidos",
            "tipo": "Tecnico",
            "jogo": "Valorant",
            "equipe" : "EG",
        },
        {
            "_id": 25,
            "nome": "Guo",
            "nickname": "Haodong",
            "idade": 21,
            "pais": "China",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "EDG",
        },
        {
            "_id": 26,
            "nome": "Zheng",
            "nickname": "ZmijjKK",
            "idade": 17,
            "pais": "China",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "EDG",
        },
        {
            "_id": 27,
            "nome": "Wang",
            "nickname": "Nobody",
            "idade": 20,
            "pais": "China",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "EDG",
        },
        {
            "_id": 28,
            "nome": "Wan",
            "nickname": "CHICHOO",
            "idade": 21,
            "pais": "China",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "EDG",
        },
        {
            "_id": 29,
            "nome": "Zhang",
            "nickname": "Smoggy",
            "idade": 18,
            "pais": "China",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "EDG",
        },
        {
            "_id": 30,
            "nome": "Lo Wen-Hsin",
            "nickname": "AfteR",
            "idade": 30,
            "pais": "China",
            "tipo": "Tecnico",
            "jogo": "Valorant",
            "equipe" : "EDG",
        },
        {
            "_id": 31,
            "nome": "Jake",
            "nickname": "Boaster",
            "idade": 22,
            "pais": "Inglaterra",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Fnatic",
        },
        {
            "_id": 32,
            "nome": "Leo",
            "nickname": "Leo",
            "idade": 19,
            "pais": "Suecia",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Fnatic",
        },
        {
            "_id": 33,
            "nome": "Nikita",
            "nickname": "Derke",
            "idade": 23,
            "pais": "Finlandia",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Fnatic",
        },
        {
            "_id": 34,
            "nome": "Timofey",
            "nickname": "Chronicle",
            "idade": 23,
            "pais": "Russia",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Fnatic",
        },
        {
            "_id": 35,
            "nome": "Emir",
            "nickname": "Alfajer",
            "idade": 22,
            "pais": "Tunisia",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Fnatic",
        },
        {
            "_id": 36,
            "nome": "Ander",
            "nickname": "Mini",
            "idade": 29,
            "pais": "Inglaterra",
            "tipo": "Tecnico",
            "jogo": "Valorant",
            "equipe" : "Fnatic",
        },
        {
            "_id": 37,
            "nome": "Kim",
            "nickname": "Stax",
            "idade": 22,
            "pais": "Coreia do Sul",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "DRX",
        },
        {
            "_id": 38,
            "nome": "Goo",
            "nickname": "Rb",
            "idade": 23,
            "pais": "Coreia do Sul",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "DRX",
        },
        {
            "_id": 39,
            "nome": "Kim",
            "nickname": "ZestKR",
            "idade": 21,
            "pais": "Coreia do Sul",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "DRX",
        },
        {
            "_id": 40,
            "nome": "Yuu",
            "nickname": "Buzz",
            "idade": 21,
            "pais": "Coreia do Sul",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "DRX",
        },
        {
            "_id": 41,
            "nome": "Kim Myeong",
            "nickname": "Mako",
            "idade": 24,
            "pais": "Coreia do Sul",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "DRX",
        },
        {
            "_id": 42,
            "nome": "Kim Min-soo",
            "nickname": "glow",
            "idade": 30,
            "pais": "Coreia do Sul",
            "tipo": "Tecnico",
            "jogo": "Valorant",
            "equipe" : "DRX",
        },
        {
            "_id": 43,
            "nome": "Luiz Eduardo",
            "nickname": "birizinho mira sutiã",
            "idade": 20,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Cavaleiros do Grad",
        },
        {
            "_id": 44,
            "nome": "Pedro Calheiros",
            "nickname": "pepito fiufiu",
            "idade": 21,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Cavaleiros do Grad",
        },
        {
            "_id": 45,
            "nome": "Matheus Braga",
            "nickname": "MastBraga2",
            "idade": 20,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Cavaleiros do Grad",
        },
        {
            "_id": 46,
            "nome": "Ian Braga",
            "nickname": "filho do matue",
            "idade": 20,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Cavaleiros do Grad",
        },
        {
            "_id": 47,
            "nome": "Pedro Baptista",
            "nickname": "ZequinhaBaptista",
            "idade": 20,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "Valorant",
            "equipe" : "Cavaleiros do Grad",
        },
        {
            "_id": 48,
            "nome": "Phillippe Menge",
            "nickname": "Menge",
            "idade": 20,
            "pais": "Brasil",
            "tipo": "Tecnico",
            "jogo": "Valorant",
            "equipe" : "Cavaleiros do Grad",
        },
        {
            "_id": 49,
            "nome": "Henrique Melo",
            "nickname": "MT",
            "idade": 20,
            "pais": "Brasil",
            "tipo": "Narrador",
            "jogo": "Valorant",
            "equipe" : "Transmissao",
        },
        {
            "_id": 50,
            "nome": "Bernado",
            "nickname": "Bida",
            "idade": 35,
            "pais": "Brasil",
            "tipo": "Narrador",
            "jogo": "Valorant",
            "equipe" : "Transmissao",
        },
        #VITALITY
        {
            "_id": 51,
            "nome": "Dan Madesclaire",
            "nickname": "apEX",
            "idade": 30,
            "pais": "Franca",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "Vitality",
        },
        {
            "_id": 52,
            "nome": "Emil Reif",
            "nickname": "Magisk",
            "idade": 25,
            "pais": "Dinamarca",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "Vitality",
        },
        {
            "_id": 53,
            "nome": "Mathieu Herbaut",
            "nickname": "ZywOo",
            "idade": 22,
            "pais": "Franca",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "Vitality",
        },
        {
            "_id": 54,
            "nome": "Shahar Shushan",
            "nickname": "FlameZ",
            "idade": 20,
            "pais": "Israel",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "Vitality",
        },
        {
            "_id": 55,
            "nome": "Lotan Giladi",
            "nickname": "Spinx",
            "idade": 22,
            "pais": "Israel",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "Vitality",
        },
        {
            "_id": 56,
            "nome": "Danny Sørensen",
            "nickname": "zonic",
            "idade": 37,
            "pais": "Dinamarca",
            "tipo": "Tecnico",
            "jogo": "CS",
            "equipe" : "Vitality",
        },

        #ENCE
        {
            "_id": 57,
            "nome": "Marco Pfeiffer",
            "nickname": "Snappi",
            "idade": 33,
            "pais": "Dinamarca",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "ENCE",
        },
        {
            "_id": 58,
            "nome": "Guy Iluz",
            "nickname": "NertZ",
            "idade": 24,
            "pais": "Israel",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "ENCE",
        },
        {
            "_id": 59,
            "nome": "Pavle Bošković",
            "nickname": "Maden",
            "idade": 24,
            "pais": "Montenegro",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "ENCE",
        },
        {
            "_id": 60,
            "nome": "Paweł Dycha",
            "nickname": "dycha",
            "idade": 26,
            "pais": "Polonia",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "ENCE",
        },
        {
            "_id": 61,
            "nome": "Alvaro Garcia",
            "nickname": "SunPayus",
            "idade": 24,
            "pais": "Espanha",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "ENCE",
        },
        {
            "_id": 62,
            "nome": "Eetu Saha",
            "nickname": "sAw",
            "idade": 31,
            "pais": "Finlandia",
            "tipo": "Tecnico",
            "jogo": "CS",
            "equipe" : "ENCE",
        },


        #G2
        {
            "_id": 63,
            "nome": " Nikola Kovač",
            "nickname": "NiKo",
            "idade": 26,
            "pais": "Bosnia",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "G2",
        },
        {
            "_id": 64,
            "nome": "Nemanja Kovač",
            "nickname": "huNter-",
            "idade": 27,
            "pais": "Bosnia",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "G2",
        },
        {
            "_id": 65,
            "nome": "Justin Savage",
            "nickname": "jks",
            "idade": 27,
            "pais": "Australia",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "G2",
        },
        {
            "_id": 66,
            "nome": "Rasmus Nielsen",
            "nickname": "HooXi",
            "idade": 28,
            "pais": "Dinamarca",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "G2",
        },
        {
            "_id": 67,
            "nome": "Ilya Osipov",
            "nickname": "m0NESY",
            "idade": 18,
            "pais": "Russia",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "G2",
        },
        {
            "_id": 68,
            "nome": "Jan Müller",
            "nickname": "Swani",
            "idade": 28,
            "pais": "Alemanha",
            "tipo": "Tecnico",
            "jogo": "CS",
            "equipe" : "G2",
        },


        #Heroic

        {
            "_id": 69,
            "nome": "Casper Møller",
            "nickname": "cadiaN",
            "idade": 28,
            "pais": "Dinamarca",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "Heroic",
        },
        {
            "_id": 70,
            "nome": "Martin Lund",
            "nickname": "stavn",
            "idade": 21,
            "pais": "Dinamarca",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "Heroic",
        },
        {
            "_id": 71,
            "nome": "René Madsen",
            "nickname": "TeSeS",
            "idade": 22,
            "pais": "Dinamarca",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "Heroic",
        },
        {
            "_id": 72,
            "nome": "Rasmus Beck",
            "nickname": "sjuush",
            "idade": 24,
            "pais": "Dinamarca",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "Heroic",
        },
        {
            "_id": 73,
            "nome": "Jakob Nygaard",
            "nickname": "jabbi",
            "idade": 20,
            "pais": "Dinamarca",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe" : "Heroic",
        },
        {
            "_id": 74,
            "nome": "Richard Landström",
            "nickname": "Xizt",
            "idade": 32,
            "pais": "Suecia",
            "tipo": "Tecnico",
            "jogo": "CS",
            "equipe" : "Heroic",
        },

        {
            "_id": 75,
            "nome": "Willian Moreira Lemos Rodrigues",
            "nickname": "gORDOx",
            "idade": 35,
            "pais": "Brasil",
            "tipo": "Narrador",
            "jogo": "CS",
            "equipe" : "Transmissao",
        },
        {
            "_id": 76,
            "nome": "Gabriel Toledo",
            "nickname": "Fallen",
            "idade": 32,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "Furia",
        },
        {
            "_id": 77,
            "nome": "Marcelo Cespedes",
            "nickname": "Chelo",
            "idade": 25,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "Furia",
        },
        {   
            "_id": 78,
            "nome": "Kaike Cerato",
            "nickname": "KSCERATO",
            "idade": 23,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "Furia",
        },
        {
            "_id": 79,
            "nome": "Andrei Piovezan",
            "nickname": "ArT",
            "idade": 27,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "Furia",
        },
        {
            "_id": 80,
            "nome": "Yuri Boian",
            "nickname": "Yuurih",
            "idade": 23,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "Furia",
        },
        {
            "_id": 81,
            "nome": "Nicholas Nogueira",
            "nickname": "guerri",
            "idade": 33,
            "pais": "Brasil",
            "tipo": "Tecnico",
            "jogo": "CS",
            "equipe": "Furia",
        },
        {
            "_id": 82,
            "nome": "Håvard Nygaard	",
            "nickname": "rain",
            "idade": 29,
            "pais": "Noruega",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "FaZe",
        },
        {
            "_id": 83,
            "nome": "Helvijs Saukants",
            "nickname": "broky",
            "idade": 22,
            "pais": "Letonia",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "FaZe",
        },
        {
            "_id": 84,
            "nome": "Russel Van Dulken",
            "nickname": "Twistzz",
            "idade": 23,
            "pais": "Canada",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "FaZe",
        },
        {
            "_id": 85,
            "nome": "Finn Andersen",
            "nickname": "karrigan",
            "idade": 33,
            "pais": "Dinamarca",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "FaZe",
        },
        {
            "_id": 86,
            "nome": "Robin Kool",
            "nickname": "ropz",
            "idade": 23,
            "pais": "Estonia",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "FaZe",
        },
        {
            "_id": 87,
            "nome": "Filip Kubski",
            "nickname": "NEO",
            "idade": 36,
            "pais": "Polonia",
            "tipo": "Tecnico",
            "jogo": "CS",
            "equipe": "FaZe",
        },
        {
            "_id": 88,
            "nome": "Benjamin Bremer",
            "nickname": "blameF",
            "idade": 26,
            "pais": "Dinamarca",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "Astralis",
        },
        {
            "_id": 89,
            "nome": "Nicolai Reedtz",
            "nickname": "dev1ce",
            "idade": 27,
            "pais": "Dinamarca",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "Astralis",
        },
        {
            "_id": 90,
            "nome": "	Christian Andersen",
            "nickname": "Buzz",
            "idade": 20,
            "pais": "Dinamarca",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "Astralis",
        },
        {
            "_id": 91,
            "nome": "Victor Staehr",
            "nickname": "Staehr",
            "idade": 19,
            "pais": "Dinamarca",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "Astralis",
        },
        {
            "_id": 92,
            "nome": "Johannes Borup",
            "nickname": "b0RUP",
            "idade": 23,
            "pais": "Dinamarca",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "Astralis",
        },
        {
            "_id": 93,
            "nome": "Peter Toftbo",
            "nickname": "casle",
            "idade": 37,
            "pais": "Dinamarca",
            "tipo": "Tecnico",
            "jogo": "CS",
            "equipe": "Astralis",
        },
        {
            "_id": 94,
            "nome": "Raphael Lacerda",
            "nickname": "exit",
            "idade": 27,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "MIBR",
        },
        {
            "_id": 95,
            "nome": "Breno Poletto",
            "nickname": "brnz4n",
            "idade": 20,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "MIBR",
        },
        {
            "_id": 96,
            "nome": "Felipe Yuji",
            "nickname": "insani",
            "idade": 19,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "MIBR",
        },
        {
            "_id": 97,
            "nome": "André Abreu",
            "nickname": "drop",
            "idade": 19,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "MIBR",
        },
        {
            "_id": 98,
            "nome": "Rafael Costa",
            "nickname": "saffee",
            "idade": 28,
            "pais": "Brasil",
            "tipo": "Jogador",
            "jogo": "CS",
            "equipe": "MIBR",
        },
        {
            "_id": 99,
            "nome": "Bruno Lima",
            "nickname": "BIT",
            "idade": 33,
            "pais": "Brasil",
            "tipo": "Tecnico",
            "jogo": "CS",
            "equipe": "MIBR",
        },
        {
            "_id": 100,
            "nome": "Alexandre Borba",
            "nickname": "gAuLeS",
            "idade": 39,
            "pais": "Brasil",
            "tipo": "Narrador",
            "jogo": "CS",
            "equipe": "Transmissao",
        },
    ])

times = db["times_tabela"]

times.insert_many([
    {
        "_id": 101,
        "nome" : "LOUD",
        "atletas": [doc for doc in pessoas.find(
            {"tipo": "Jogador", "equipe" : "LOUD"})],
        "tecnico": pessoas.find_one({"tipo" : "Tecnico", "equipe" : "LOUD"}),
        "pais": "Brasil",
        "jogo" : "Valorant",
        "CampeaoMundial" : "sim"
    },
    {
        "_id": 102,
        "nome" : "Furia",
        "atletas": [doc for doc in pessoas.find(
            {"tipo": "Jogador", "equipe" : "Furia", "jogo" : "Valorant"})],
        "tecnico": None,
        "pais": "Brasil",
        "jogo" : "Valorant"
    },
    {
        "_id": 103,
        "nome" : "Sentinels",
        "atletas": [doc for doc in pessoas.find(
            {"tipo": "Jogador", "equipe" : "Sentinels"})],
        "tecnico": pessoas.find_one({"tipo" : "Tecnico", "equipe" : "Sentinels"}),
        "pais": "Estados Unidos",
        "jogo" : "Valorant"
    },
    {
        "_id": 104,
        "nome" : "EG",
        "atletas": [doc for doc in pessoas.find(
            {"tipo": "Jogador", "equipe" : "EG"})],
        "tecnico": pessoas.find_one({"tipo" : "Tecnico", "equipe" : "EG"}),
        "pais": "Estados Unidos",
        "jogo" : "Valorant"
    },
    {
        "_id": 105,
        "nome" : "EDG",
        "atletas": [doc for doc in pessoas.find(
            {"tipo": "Jogador", "equipe" : "EDG"})],
        "tecnico": pessoas.find_one({"tipo" : "Tecnico", "equipe" : "EDG"}),
        "pais": "China",
        "jogo" : "Valorant"
    },
    {
        "_id": 106,
        "nome" : "Fnatic",
        "atletas": [doc for doc in pessoas.find(
            {"tipo": "Jogador", "equipe" : "Fnatic"})],
        "tecnico": pessoas.find_one({"tipo" : "Tecnico", "equipe" : "Fnatic"}),
        "pais": "Inglaterra",
        "jogo" : "Valorant"
    },
    {
        "_id": 107,
        "nome" : "DRX",
        "atletas": [doc for doc in pessoas.find(
            {"tipo": "Jogador", "equipe" : "DRX"})],
        "tecnico": pessoas.find_one({"tipo" : "Tecnico", "equipe" : "DRX"}),
        "pais": "Coreia do Sul",
        "jogo" : "Valorant"
    },
    {
        "_id": 108,
        "nome" : "Cavaleiros do Grad",
        "atletas": [doc for doc in pessoas.find(
            {"tipo": "Jogador", "equipe" : "Cavaleiros do Grad"})],
        "tecnico": pessoas.find_one({"tipo" : "Tecnico", "equipe" : "Cavaleiros do Grad"}),
        "pais": "Brasil",
        "jogo" : "Valorant"
    },
    {
        "_id": 109,
        "nome" : "Vitality",
        "atletas": [doc for doc in pessoas.find(
            {"tipo": "Jogador", "equipe" : "Vitality"})],
        "tecnico": pessoas.find_one({"tipo" : "Tecnico", "equipe" : "Vitality"}),
        "pais": "França",
        "jogo" : "CS"
    },
    {
        "_id": 110,
        "nome" : "ENCE",
        "atletas": [doc for doc in pessoas.find(
            {"tipo": "Jogador", "equipe" : "ENCE"})],
        "tecnico": pessoas.find_one({"tipo" : "Tecnico", "equipe" : "ENCE"}),
        "pais": "Finlandia",
        "jogo" : "CS"
    },
    {
        "_id": 111,
        "nome" : "G2",
        "atletas": [doc for doc in pessoas.find(
            {"tipo": "Jogador", "equipe" : "G2"})],
        "tecnico": pessoas.find_one({"tipo" : "Tecnico", "equipe" : "G2"}),
        "pais": "França",
        "jogo" : "CS"
    },
    {
        "_id": 112,
        "nome" : "Heroic",
        "atletas": [doc for doc in pessoas.find(
            {"tipo": "Jogador", "equipe" : "Heroic"})],
        "tecnico": pessoas.find_one({"tipo" : "Tecnico", "equipe" : "Heroic"}),
        "pais": "Dinamarca",
        "jogo" : "CS"
    },
    {
        "_id": 113,
        "nome" : "Furia",
        "atletas": [doc for doc in pessoas.find(
            {"tipo": "Jogador", "equipe" : "Furia", "jogo" : "CS"})],
        "tecnico": pessoas.find_one({"tipo" : "Tecnico", "equipe" : "Furia", "jogo" : "CS"}),
        "pais": "Brasil",
        "jogo" : "CS"
    },
    {
        "_id": 114,
        "nome" : "FaZe",
        "atletas": [doc for doc in pessoas.find(
            {"tipo": "Jogador", "equipe" : "FaZe"})],
        "tecnico": pessoas.find_one({"tipo" : "Tecnico", "equipe" : "FaZe"}),
        "pais": "Estados Unidos",
        "jogo" : "CS"
    },
    {
        "_id": 115,
        "nome" : "Astralis",
        "atletas": [doc for doc in pessoas.find(
            {"tipo": "Jogador", "equipe" : "Astralis"})],
        "tecnico": pessoas.find_one({"tipo" : "Tecnico", "equipe" : "Astralis"}),
        "pais": "Dinamarca",
        "jogo" : "CS"
    },
    {
        "_id": 116,
        "nome" : "MIBR",
        "atletas": [doc for doc in pessoas.find(
            {"tipo": "Jogador", "equipe" : "MIBR"})],
        "tecnico": pessoas.find_one({"tipo" : "Tecnico", "equipe" : "MIBR"}),
        "pais": "Brasil",
        "jogo" : "CS"
    },
])

partidas = db["partidas_tabela"]

partidas.insert_many([

    {   
        "_id" : 1000,
        "nome" : "Valorant - Quartas Final - LOUD x FURIA",
        "datahora_inicio" : "18:00 11/09/2023",
        "datahora_fim" : "22:00 11/09/2023",
        "cidade" : "Recife",
        "competidores" : [times.find_one({"nome": "LOUD", "jogo": "Valorant"}), times.find_one({"nome": "Furia", "jogo": "Valorant"})],
        "estadio" : "Geraldao",
        "capacidade" : 10000,
        "vencedor" : times.find_one({"nome": "LOUD"})
    },
    {   
        "_id" : 1001,
        "nome" : "Valorant - Quartas Final - Sentinels x EG",
        "datahora_inicio" : "18:00 12/09/2023",
        "datahora_fim" : "22:00 12/09/2023",
        "cidade" : "Recife",
        "competidores" : [times.find_one({"nome": "Sentinels"}), times.find_one({"nome": "EG"})],
        "estadio" : "Geraldao",
        "capacidade" : 10000,
        "vencedor" : times.find_one({"nome": "EG"})
    },
    {   
        "_id" : 1002,
        "nome" : "Valorant - Quartas Final - Fnatic x EDG",
        "datahora_inicio" : "18:00 13/09/2023",
        "datahora_fim" : "22:00 13/09/2023",
        "cidade" : "Recife",
        "competidores" : [times.find_one({"nome": "Fnatic"}), times.find_one({"nome": "EDG"})],
        "estadio" : "Geraldao",
        "capacidade" : 10000,
        "vencedor" : times.find_one({"nome": "Fnatic"})
    },
    {   
        "_id" : 1003,
        "nome" : "Valorant - Quartas Final - Cavaleiros do Grad x DRX",
        "datahora_inicio" : "18:00 14/09/2023",
        "datahora_fim" : "22:00 14/09/2023",
        "cidade" : "Recife",
        "competidores" : [times.find_one({"nome": "Cavaleiros do Grad"}), times.find_one({"nome": "DRX"})],
        "estadio" : "Geraldao",
        "capacidade" : 10000,
        "vencedor" : times.find_one({"nome": "Cavaleiros do Grad"})
    },
    {   
        "_id" : 1004,
        "nome" : "Valorant - Semi Final - LOUD x EG",
        "datahora_inicio" : "13:00 16/09/2023",
        "datahora_fim" : "18:00 16/09/2023",
        "cidade" : "Recife",
        "competidores" : [times.find_one({"nome": "LOUD"}), times.find_one({"nome": "EG"})],
        "estadio" : "Geraldao",
        "capacidade" : 10000,
        "vencedor" : times.find_one({"nome": "LOUD"})
    },
    {   
        "_id" : 1005,
        "nome" : "Valorant - Semi Final - Fnatic x Cavaleiros do Grad",
        "datahora_inicio" : "19:00 16/09/2023",
        "datahora_fim" : "23:00 16/09/2023",
        "cidade" : "Recife",
        "competidores" : [times.find_one({"nome": "Fnatic"}), times.find_one({"nome": "Cavaleiros do Grad"})],
        "estadio" : "Geraldao",
        "capacidade" : 10000,
        "vencedor" : times.find_one({"nome": "Cavaleiros do Grad"})
    },
    {   
        "_id" : 1006,
        "nome" : "Valorant - Final - LOUD x Cavaleiros do Grad",
        "datahora_inicio" : "13:00 18/09/2023",
        "datahora_fim" : "18:00 18/09/2023",
        "cidade" : "Recife",
        "competidores" : [times.find_one({"nome": "LOUD"}), times.find_one({"nome": "Cavaleiros do Grad"})],
        "estadio" : "113 club",
        "capacidade" : 113000,
        "vencedor" : times.find_one({"nome": "Cavaleiros do Grad"})
    },
    {   
        "_id" : 1007,
        "nome" : "CS - Quartas de Final - Vitality x ENCE",
        "datahora_inicio" : "13:00 20/09/2023",
        "datahora_fim" : "18:00 20/09/2023",
        "cidade" : "Recife",
        "competidores" : [times.find_one({"nome": "Vitality"}), times.find_one({"nome": "ENCE"})],
        "estadio" : "Arruda",
        "capacidade" : 60000,
        "vencedor" : times.find_one({"nome": "Vitality"})
    },
    {   
        "_id" : 1008,
        "nome" : "CS - Quartas de Final - G2 x Heroic",
        "datahora_inicio" : "13:00 21/09/2023",
        "datahora_fim" : "18:00 21/09/2023",
        "cidade" : "Recife",
        "competidores" : [times.find_one({"nome": "G2"}), times.find_one({"nome": "Heroic"})],
        "estadio" : "Arruda",
        "capacidade" : 60000,
        "vencedor" : times.find_one({"nome": "Heroic"})
    },
    {   
        "_id" : 1009,
        "nome" : "CS - Quartas de Final - Furia x FaZe",
        "datahora_inicio" : "13:00 22/09/2023",
        "datahora_fim" : "18:00 22/09/2023",
        "cidade" : "Recife",
        "competidores" : [times.find_one({"nome": "Furia", "jogo" : "CS"}), times.find_one({"nome": "FaZe"})],
        "estadio" : "Arruda",
        "capacidade" : 60000,
        "vencedor" : times.find_one({"nome": "Furia"})
    },
    {   
        "_id" : 1010,
        "nome" : "CS - Quartas de Final - MIBR x Astralis",
        "datahora_inicio" : "13:00 23/09/2023",
        "datahora_fim" : "18:00 23/09/2023",
        "cidade" : "Recife",
        "competidores" : [times.find_one({"nome": "MIBR"}), times.find_one({"nome": "Astralis"})],
        "estadio" : "Arruda",
        "capacidade" : 60000,
        "vencedor" : times.find_one({"nome": "MIBR"})
    },
    {   
        "_id" : 1011,
        "nome" : "CS - Semi Final - Vitality x Heroic",
        "datahora_inicio" : "13:00 24/09/2023",
        "datahora_fim" : "18:00 24/09/2023",
        "cidade" : "Recife",
        "competidores" : [times.find_one({"nome": "Vitality"}), times.find_one({"nome": "Heroic"})],
        "estadio" : "Arruda",
        "capacidade" : 60000,
        "vencedor" : times.find_one({"nome": "Heroic"})
    },
    {   
        "_id" : 1012,
        "nome" : "CS - Semi Final - Furia x MIBR",
        "datahora_inicio" : "13:00 25/09/2023",
        "datahora_fim" : "18:00 25/09/2023",
        "cidade" : "Recife",
        "competidores" : [times.find_one({"nome": "Furia"}), times.find_one({"nome": "MIBR"})],
        "estadio" : "Arruda",
        "capacidade" : 60000,
        "vencedor" : times.find_one({"nome": "Furia"})
    },
    {   
        "_id" : 1013,
        "nome" : "CS - Final - Heroic x Furia",
        "datahora_inicio" : "13:00 25/09/2023",
        "datahora_fim" : "18:00 25/09/2023",
        "cidade" : "Recife",
        "competidores" : [times.find_one({"nome": "Furia", "jogo" : "CS"}), times.find_one({"nome": "Heroic"})],
        "estadio" : "Anfiteatro Riomar",
        "capacidade" : 5000,
        "vencedor" : times.find_one({"nome": "Furia"})
    },
])

transmissao = db["transmissao_tabela"]

transmissao.insert_many([
    {
        "_id" : 500,
        "partida" : partidas.find_one({"nome": "Valorant - Quartas Final - LOUD x FURIA"}),
        "narrador" : pessoas.find_one({"nickname" : "MT"})
    },
    {
        "_id" : 501,
        "partida" : partidas.find_one({"nome": "Valorant - Quartas Final - Sentinels x EG"}),
        "narrador" : pessoas.find_one({"nickname" : "Bida"})
    },
    {
        "_id" : 502,
        "partida" : partidas.find_one({"nome": "Valorant - Quartas Final - Fnatic x EDG"}),
        "narrador" : pessoas.find_one({"nickname" : "MT"})
    },
    {
        "_id" : 503,
        "partida" : partidas.find_one({"nome" : "Valorant - Quartas Final - Cavaleiros do Grad x DRX"}),
        "narrador" : pessoas.find_one({"nickname" : "Bida"})
    },
    {
        "_id" : 504,
        "partida" : partidas.find_one({"nome": "Valorant - Semi Final - LOUD x EG"}),
        "narrador" : pessoas.find_one({"nickname" : "MT"})
    },
    {
        "_id" : 505,
        "partida" : partidas.find_one({"nome": "Valorant - Semi Final - Fnatic x Cavaleiros do Grad"}),
        "narrador" : pessoas.find_one({"nickname" : "Bida"})
    },
    {
        "_id" : 506,
        "partida" : partidas.find_one({"nome": "Valorant - Final - LOUD x Cavaleiros do Grad"}),
        "narrador" : pessoas.find_one({"nickname" : "MT"})
    },
    {
        "_id" : 507,
        "partida" : partidas.find_one({"nome": "CS - Quartas de Final - Vitality x ENCE"}),
        "narrador" : pessoas.find_one({"nickname" : "gORDOx"})
    },
    {
        "_id" : 508,
        "partida" : partidas.find_one({"nome": "CS - Quartas de Final - G2 x Heroic"}),
        "narrador" : pessoas.find_one({"nickname" : "gAuLeS"})
    },
    {
        "_id" : 509,
        "partida" : partidas.find_one({"nome": "CS - Quartas de Final - Furia x FaZe"}),
        "narrador" : pessoas.find_one({"nickname" : "gORDOx"})
    },
    {
        "_id" : 510,
        "partida" : partidas.find_one({"nome": "CS - Quartas de Final - MIBR x Astralis"}),
        "narrador" : pessoas.find_one({"nickname" : "gAuLeS"})
    },
    {
        "_id" : 511,
        "partida" : partidas.find_one({"nome": "CS - Semi Final - Vitality x Heroic"}),
        "narrador" : pessoas.find_one({"nickname" : "gORDOx"})
    },
    {
        "_id" : 512,
        "partida" : partidas.find_one({"nome": "CS - Semi Final - Furia x MIBR"}),
        "narrador" : pessoas.find_one({"nickname" : "gAuLeS"})
    },
    {
        "_id" : 513,
        "partida" : partidas.find_one({"nome": "CS - Final - Heroic x Furia"}),
        "narrador" : pessoas.find_one({"nickname" : "gAuLeS"})
    },
])